modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
credits="Thanks for this example mod goes to Java" #optional
authors="Sauuuuucey" #optional

[[mods]] #mandatory
modId="sauuuuuceysores" #mandatory
version="1.2-release" #mandatory
displayName="Sauuuuucey's Ores" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Sauuuuucey's Ores adds adding new materials and ores to the game, in a realistic-esque fashion, to make the underground feel less empty while providing new ways to utilize ores into new tools and armors. 
How can it be called Minecraft when there's like 3 usable ores?¿
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"